# Generated by Django 5.1.3 on 2026-03-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEPO', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
