# Generated by Django 5.1.3 on 2026-03-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEPO', '0004_student_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matric',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
