# Generated by Django 5.1.3 on 2026-03-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEPO', '0008_remove_passwordresetcode_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to='NEPO.student'),
        ),
    ]
